---
title: "Untitled"
author: "Jordan Brennan"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(jsonlite)
library(tidyverse)
library(httr)
```



```{r}
library(PetfindeR)
pf =Petfinder(key="kUGpgD5ZYY4Ni6luxnisNP0LDTLRJZlJXVfZqqZGJ7RYT5nyON", secret ="2s07it7LeGkAaoA3gANxb0j1N8FWVCWgjwnnqV6l")
```


```{r}
# All animal types and their relevant data.
all_types = pf$animal_types()

# Returning data for a single animal type
dogs = pf$animal_types('dog')

# Getting multiple animal types at once
cat_dog_rabbit_types = pf$animal_types(c('cat', 'dog', 'rabbit'))
```




```{r}
# Getting first 20 results without any search criteria
animals = pf$animals()

cats = pf$animals(animal_type = 'cat', gender = 'female', status = 'adoptable', 
                  location = 'Seattle, WA', distance = 10, results_per_page = 50, pages = 2)
```



```{r}
# Return the first 1,000 animal welfare organizations

organizations = pf$organizations(results_per_page = 100, pages = 10)

# Get organizations in the state of Washington

wa_organizations = pf$organizations(state='WA')
```





